### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by albertodeago** [cronitorio/cronitor-rum-nextjs#2]
Hello, thanks for the cool integration
Not sure if this is an issue or a question...
I'm trying to use it in my next.js app (still using v12.x) and I cannot install it because this package set as peer deps next v13

Is this intended?

**Comment by anthonynsimon** [comment]
Hi, as of version 0.2.0 of this package only Next.js 13 or later is supported due to breaking changes in the Next API. For previous versions of Next.js please install version 0.1.0 of this package.

**Comment by albertodeago** [comment]
oh ok, thanks man
